-- Cache Lua / WoW API
local format = string.format
local GetCVarBool = GetCVarBool
local ReloadUI = ReloadUI
local StopMusic = StopMusic
local GetAddOnMetadata = (C_AddOns and C_AddOns.GetAddOnMetadata) or GetAddOnMetadata

-- Don't worry about this
local addon, Private = ...
local Version = GetAddOnMetadata(addon, "Version")

-- Change this line and use a unique name for your plugin.
local MyPluginName = "AscendedUI"

-- Create references to ElvUI internals
local E, L, V, P, G = unpack(ElvUI)

-- Create reference to LibElvUIPlugin
local EP = LibStub("LibElvUIPlugin-1.0")

-- Create a new ElvUI module so ElvUI can handle initialization when ready
local mod = E:NewModule(MyPluginName, "AceHook-3.0", "AceEvent-3.0", "AceTimer-3.0");

-- This function will hold your layout settings
local function SetupLayout(layout)

	-- PUT YOUR EXPORTED PROFILE/SETTINGS BELOW HERE
	-- Profile settings below
	E.db["WT"]["combat"]["raidMarkers"]["enable"] = false
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["bindFont"]["name"] = "Beep-Black"
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["bindFont"]["style"] = "SHADOWOUTLINE"
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["countFont"]["name"] = "Beep-Black"
E.db["WT"]["item"]["extraItemsBar"]["bar1"]["countFont"]["style"] = "SHADOWOUTLINE"
E.db["WT"]["item"]["extraItemsBar"]["enable"] = false
E.db["WT"]["item"]["inspect"]["levelText"]["name"] = "Beep-Black"
E.db["WT"]["item"]["itemLevel"]["flyout"]["font"]["name"] = "Beep-Black"
E.db["WT"]["item"]["itemLevel"]["flyout"]["font"]["style"] = "SHADOWOUTLINE"
E.db["WT"]["item"]["itemLevel"]["scrappingMachine"]["font"]["name"] = "Beep-Black"
E.db["WT"]["item"]["itemLevel"]["scrappingMachine"]["font"]["style"] = "SHADOWOUTLINE"
E.db["WT"]["misc"]["gameBar"]["additionalText"]["font"]["name"] = "Beep-Black"
E.db["WT"]["misc"]["gameBar"]["additionalText"]["font"]["style"] = "SHADOWOUTLINE"
E.db["WT"]["misc"]["gameBar"]["enable"] = false
E.db["WT"]["misc"]["gameBar"]["time"]["font"]["name"] = "Beep-Black"
E.db["WT"]["misc"]["gameBar"]["time"]["font"]["style"] = "SHADOWOUTLINE"
E.db["WT"]["quest"]["switchButtons"]["enable"] = false
E.db["WT"]["quest"]["turnIn"]["enable"] = false
E.db["WT"]["social"]["chatBar"]["enable"] = false
E.db["WeakAuras"]["cooldown"]["fonts"]["font"] = "Beep-Black"
E.db["WeakAuras"]["cooldown"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar1"]["backdrop"] = true
E.db["actionbar"]["bar1"]["backdropSpacing"] = 1
E.db["actionbar"]["bar1"]["buttonHeight"] = 36
E.db["actionbar"]["bar1"]["buttonSize"] = 37
E.db["actionbar"]["bar1"]["buttonSpacing"] = 1
E.db["actionbar"]["bar1"]["buttons"] = 8
E.db["actionbar"]["bar1"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar1"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar1"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar1"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar1"]["keepSizeRatio"] = false
E.db["actionbar"]["bar1"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar1"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar10"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar10"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar10"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar10"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar10"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar10"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar2"]["backdrop"] = true
E.db["actionbar"]["bar2"]["backdropSpacing"] = 0
E.db["actionbar"]["bar2"]["buttonHeight"] = 31
E.db["actionbar"]["bar2"]["buttonSize"] = 37
E.db["actionbar"]["bar2"]["buttonSpacing"] = 1
E.db["actionbar"]["bar2"]["buttons"] = 7
E.db["actionbar"]["bar2"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar2"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar2"]["enabled"] = true
E.db["actionbar"]["bar2"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar2"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar2"]["keepSizeRatio"] = false
E.db["actionbar"]["bar2"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar2"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar2"]["targetReticle"] = false
E.db["actionbar"]["bar3"]["backdropSpacing"] = 1
E.db["actionbar"]["bar3"]["buttonSize"] = 25
E.db["actionbar"]["bar3"]["buttonSpacing"] = 1
E.db["actionbar"]["bar3"]["buttons"] = 12
E.db["actionbar"]["bar3"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar3"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar3"]["enabled"] = false
E.db["actionbar"]["bar3"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar3"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar3"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar3"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar4"]["backdrop"] = false
E.db["actionbar"]["bar4"]["backdropSpacing"] = 1
E.db["actionbar"]["bar4"]["buttonSize"] = 25
E.db["actionbar"]["bar4"]["buttonSpacing"] = 1
E.db["actionbar"]["bar4"]["buttonsPerRow"] = 12
E.db["actionbar"]["bar4"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar4"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar4"]["enabled"] = false
E.db["actionbar"]["bar4"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar4"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar4"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar4"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar4"]["point"] = "BOTTOMLEFT"
E.db["actionbar"]["bar5"]["backdropSpacing"] = 1
E.db["actionbar"]["bar5"]["buttonSize"] = 25
E.db["actionbar"]["bar5"]["buttonSpacing"] = 1
E.db["actionbar"]["bar5"]["buttons"] = 12
E.db["actionbar"]["bar5"]["buttonsPerRow"] = 12
E.db["actionbar"]["bar5"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar5"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar5"]["enabled"] = false
E.db["actionbar"]["bar5"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar5"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar5"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar5"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar6"]["backdropSpacing"] = 1
E.db["actionbar"]["bar6"]["buttonSize"] = 25
E.db["actionbar"]["bar6"]["buttonSpacing"] = 1
E.db["actionbar"]["bar6"]["buttons"] = 6
E.db["actionbar"]["bar6"]["buttonsPerRow"] = 1
E.db["actionbar"]["bar6"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar6"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar6"]["enabled"] = true
E.db["actionbar"]["bar6"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar6"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar6"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar6"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar6"]["mouseover"] = true
E.db["actionbar"]["bar6"]["point"] = "TOPRIGHT"
E.db["actionbar"]["bar7"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar7"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar7"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar7"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar7"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar7"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar8"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar8"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar8"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar8"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar8"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar8"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar9"]["countFont"] = "Beep-Black"
E.db["actionbar"]["bar9"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar9"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["bar9"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["bar9"]["macroFont"] = "Beep-Black"
E.db["actionbar"]["bar9"]["macroFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["barPet"]["backdrop"] = false
E.db["actionbar"]["barPet"]["backdropSpacing"] = 1
E.db["actionbar"]["barPet"]["buttonSize"] = 17
E.db["actionbar"]["barPet"]["buttonSpacing"] = 1
E.db["actionbar"]["barPet"]["buttonsPerRow"] = 10
E.db["actionbar"]["barPet"]["countFont"] = "Beep-Black"
E.db["actionbar"]["barPet"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["barPet"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["barPet"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["barPet"]["mouseover"] = true
E.db["actionbar"]["barPet"]["point"] = "BOTTOMLEFT"
E.db["actionbar"]["colorSwipeNormal"]["a"] = 0.80000001192093
E.db["actionbar"]["cooldown"]["fonts"]["font"] = "Beep-Black"
E.db["actionbar"]["cooldown"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["equippedItem"] = true
E.db["actionbar"]["extraActionButton"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["extraActionButton"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["flyoutSize"] = 19
E.db["actionbar"]["font"] = "Beep-Black"
E.db["actionbar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["fontSize"] = 11
E.db["actionbar"]["globalFadeAlpha"] = 1
E.db["actionbar"]["movementModifier"] = "ALT"
E.db["actionbar"]["stanceBar"]["backdropSpacing"] = 1
E.db["actionbar"]["stanceBar"]["buttonSize"] = 20
E.db["actionbar"]["stanceBar"]["buttonSpacing"] = 1
E.db["actionbar"]["stanceBar"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["stanceBar"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["stanceBar"]["point"] = "BOTTOMLEFT"
E.db["actionbar"]["vehicleExitButton"]["hotkeyFont"] = "Beep-Black"
E.db["actionbar"]["vehicleExitButton"]["hotkeyFontOutline"] = "SHADOWOUTLINE"
E.db["actionbar"]["vehicleExitButton"]["size"] = 50
E.db["actionbar"]["zoneActionButton"]["scale"] = 2
E.db["auras"]["buffs"]["countFont"] = "Beep-Black"
E.db["auras"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["auras"]["buffs"]["countFontSize"] = 11
E.db["auras"]["buffs"]["horizontalSpacing"] = 1
E.db["auras"]["buffs"]["maxWraps"] = 2
E.db["auras"]["buffs"]["size"] = 15
E.db["auras"]["buffs"]["timeFont"] = "Beep-Black"
E.db["auras"]["buffs"]["timeFontOutline"] = "SHADOWOUTLINE"
E.db["auras"]["buffs"]["wrapAfter"] = 20
E.db["auras"]["debuffs"]["countFont"] = "Beep-Black"
E.db["auras"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["auras"]["debuffs"]["countFontSize"] = 11
E.db["auras"]["debuffs"]["horizontalSpacing"] = 1
E.db["auras"]["debuffs"]["size"] = 15
E.db["auras"]["debuffs"]["timeFont"] = "Beep-Black"
E.db["auras"]["debuffs"]["timeFontOutline"] = "SHADOWOUTLINE"
E.db["auras"]["debuffs"]["wrapAfter"] = 20
E.db["bags"]["bagSize"] = 32
E.db["bags"]["bagWidth"] = 350
E.db["bags"]["bankSize"] = 32
E.db["bags"]["bankWidth"] = 550
E.db["bags"]["cooldown"]["fonts"]["font"] = "Beep-Black"
E.db["bags"]["cooldown"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["bags"]["countFont"] = "Beep-Black"
E.db["bags"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["bags"]["countFontSize"] = 11
E.db["bags"]["itemInfoFont"] = "Beep-Black"
E.db["bags"]["itemInfoFontOutline"] = "SHADOWOUTLINE"
E.db["bags"]["itemLevelFont"] = "Beep-Black"
E.db["bags"]["itemLevelFontOutline"] = "SHADOWOUTLINE"
E.db["bags"]["itemLevelFontSize"] = 11
E.db["bags"]["junkIcon"] = true
E.db["bags"]["vendorGrays"]["enable"] = true
E.db["chat"]["emotionIcons"] = false
E.db["chat"]["fadeChatToggles"] = false
E.db["chat"]["font"] = "Beep-Black"
E.db["chat"]["fontOutline"] = "SHADOWOUTLINE"
E.db["chat"]["fontSize"] = 11
E.db["chat"]["lfgIcons"] = false
E.db["chat"]["panelBackdrop"] = "HIDEBOTH"
E.db["chat"]["panelColor"]["a"] = 0.90000000596047
E.db["chat"]["panelColor"]["b"] = 0.03921568627451
E.db["chat"]["panelColor"]["g"] = 0.03921568627451
E.db["chat"]["panelColor"]["r"] = 0.03921568627451
E.db["chat"]["panelHeight"] = 141
E.db["chat"]["panelHeightRight"] = 200
E.db["chat"]["panelWidth"] = 333
E.db["chat"]["panelWidthRight"] = 350
E.db["chat"]["tabFont"] = "Beep-Black"
E.db["chat"]["tabFontOutline"] = "SHADOWOUTLINE"
E.db["chat"]["tabFontSize"] = 11
E.db["convertPages"] = true
E.db["cooldown"]["daysColor"]["g"] = 1
E.db["cooldown"]["daysColor"]["r"] = 1
E.db["cooldown"]["expiringColor"]["b"] = 1
E.db["cooldown"]["expiringColor"]["g"] = 1
E.db["cooldown"]["fonts"]["font"] = "Beep-Black"
E.db["cooldown"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["cooldown"]["hoursColor"]["r"] = 1
E.db["cooldown"]["secondsColor"]["b"] = 1
E.db["cooldown"]["threshold"] = -1
E.db["databars"]["azerite"]["enable"] = false
E.db["databars"]["azerite"]["font"] = "Beep-Black"
E.db["databars"]["azerite"]["fontOutline"] = "SHADOWOUTLINE"
E.db["databars"]["azerite"]["height"] = 5
E.db["databars"]["azerite"]["orientation"] = "HORIZONTAL"
E.db["databars"]["azerite"]["width"] = 152
E.db["databars"]["experience"]["font"] = "Beep-Black"
E.db["databars"]["experience"]["fontOutline"] = "SHADOWOUTLINE"
E.db["databars"]["experience"]["height"] = 15
E.db["databars"]["experience"]["orientation"] = "HORIZONTAL"
E.db["databars"]["experience"]["showLevel"] = true
E.db["databars"]["experience"]["textFormat"] = "PERCENT"
E.db["databars"]["experience"]["width"] = 512
E.db["databars"]["honor"]["enable"] = false
E.db["databars"]["honor"]["font"] = "Beep-Black"
E.db["databars"]["honor"]["fontOutline"] = "SHADOWOUTLINE"
E.db["databars"]["honor"]["height"] = 32
E.db["databars"]["honor"]["orientation"] = "HORIZONTAL"
E.db["databars"]["honor"]["textFormat"] = "PERCENT"
E.db["databars"]["honor"]["width"] = 395
E.db["databars"]["reputation"]["font"] = "Beep-Black"
E.db["databars"]["reputation"]["fontOutline"] = "SHADOWOUTLINE"
E.db["databars"]["reputation"]["height"] = 32
E.db["databars"]["reputation"]["orientation"] = "HORIZONTAL"
E.db["databars"]["reputation"]["textFormat"] = "PERCENT"
E.db["databars"]["reputation"]["width"] = 395
E.db["databars"]["threat"]["font"] = "Beep-Black"
E.db["databars"]["threat"]["fontOutline"] = "SHADOWOUTLINE"
E.db["databars"]["transparent"] = false
E.db["datatexts"]["font"] = "Beep-Black"
E.db["datatexts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["datatexts"]["fontSize"] = 13
E.db["datatexts"]["panels"]["Info Panel"][1] = "DPS"
E.db["datatexts"]["panels"]["Info Panel"][2] = "Durability"
E.db["datatexts"]["panels"]["Info Panel"][3] = "Time"
E.db["datatexts"]["panels"]["Info Panel"]["battleground"] = false
E.db["datatexts"]["panels"]["Info Panel"]["enable"] = false
E.db["datatexts"]["panels"]["LeftChatDataPanel"]["enable"] = false
E.db["datatexts"]["panels"]["LeftChatDataPanel"]["left"] = ""
E.db["datatexts"]["panels"]["LeftChatDataPanel"]["middle"] = ""
E.db["datatexts"]["panels"]["LeftChatDataPanel"]["right"] = ""
E.db["datatexts"]["panels"]["MinimapPanel"][1] = "Time"
E.db["datatexts"]["panels"]["MinimapPanel"][2] = "System"
E.db["datatexts"]["panels"]["MinimapPanel"]["border"] = false
E.db["datatexts"]["panels"]["MinimapPanel"]["enable"] = false
E.db["datatexts"]["panels"]["MinimapPanel"]["numPoints"] = 1
E.db["datatexts"]["panels"]["RightChatDataPanel"]["enable"] = false
E.db["datatexts"]["panels"]["RightChatDataPanel"]["left"] = ""
E.db["datatexts"]["panels"]["RightChatDataPanel"]["middle"] = ""
E.db["datatexts"]["panels"]["RightChatDataPanel"]["right"] = ""
E.db["general"]["addonCompartment"]["font"] = "Beep-Black"
E.db["general"]["addonCompartment"]["fontOutline"] = "SHADOWOUTLINE"
E.db["general"]["addonCompartment"]["fontSize"] = 43
E.db["general"]["addonCompartment"]["hide"] = true
E.db["general"]["addonCompartment"]["size"] = 40
E.db["general"]["afk"] = false
E.db["general"]["altPowerBar"]["font"] = "Beep-Black"
E.db["general"]["altPowerBar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["general"]["autoAcceptInvite"] = true
E.db["general"]["autoRepair"] = "GUILD"
E.db["general"]["backdropcolor"]["b"] = 0
E.db["general"]["backdropcolor"]["g"] = 0
E.db["general"]["backdropcolor"]["r"] = 0
E.db["general"]["backdropfadecolor"]["a"] = 1
E.db["general"]["backdropfadecolor"]["b"] = 0
E.db["general"]["backdropfadecolor"]["g"] = 0
E.db["general"]["backdropfadecolor"]["r"] = 0
E.db["general"]["bottomPanel"] = false
E.db["general"]["bottomPanelSettings"]["transparent"] = false
E.db["general"]["font"] = "Beep-Black"
E.db["general"]["fontSize"] = 11
E.db["general"]["fontStyle"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["cooldown"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["errortext"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["errortext"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["mailbody"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["mailbody"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["objective"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["objective"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["pvpsubzone"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["pvpsubzone"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["pvpzone"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["pvpzone"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["questsmall"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["questsmall"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["questtext"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["questtext"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["questtitle"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["questtitle"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["talkingtext"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["talkingtext"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["talkingtitle"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["talkingtitle"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["worldsubzone"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["worldsubzone"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["fonts"]["worldzone"]["font"] = "Beep-Black"
E.db["general"]["fonts"]["worldzone"]["outline"] = "SHADOWOUTLINE"
E.db["general"]["guildBank"]["countFont"] = "Beep-Black"
E.db["general"]["guildBank"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["guildBank"]["itemLevelFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["itemLevel"]["itemLevelFont"] = "Beep-Black"
E.db["general"]["itemLevel"]["itemLevelFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["itemLevel"]["totalLevelFont"] = "Beep-Black"
E.db["general"]["itemLevel"]["totalLevelFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["lootRoll"]["nameFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["minimap"]["clusterBackdrop"] = false
E.db["general"]["minimap"]["icons"]["classHall"]["position"] = "BOTTOMRIGHT"
E.db["general"]["minimap"]["icons"]["classHall"]["scale"] = 1.7
E.db["general"]["minimap"]["icons"]["classHall"]["yOffset"] = 100
E.db["general"]["minimap"]["locationFont"] = "Beep-Black"
E.db["general"]["minimap"]["locationFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["minimap"]["locationFontSize"] = 18
E.db["general"]["minimap"]["resetZoom"]["time"] = 8
E.db["general"]["minimap"]["size"] = 150
E.db["general"]["minimap"]["timeFont"] = "Beep-Black"
E.db["general"]["minimap"]["timeFontOutline"] = "SHADOWOUTLINE"
E.db["general"]["objectiveFrameAutoHide"] = false
E.db["general"]["objectiveFrameAutoHideInKeystone"] = true
E.db["general"]["objectiveFrameHeight"] = 500
E.db["general"]["queueStatus"]["font"] = "Beep-Black"
E.db["general"]["queueStatus"]["fontOutline"] = "SHADOWOUTLINE"
E.db["general"]["smoothingAmount"] = 0.5
E.db["general"]["stickyFrames"] = false
E.db["general"]["talkingHeadFrameScale"] = 0.75
E.db["general"]["totems"]["growthDirection"] = "HORIZONTAL"
E.db["general"]["totems"]["size"] = 43
E.db["general"]["valuecolor"]["b"] = 1
E.db["general"]["valuecolor"]["g"] = 0.054901964962482
E.db["general"]["valuecolor"]["r"] = 0
E.db["mMT"]["afk"]["enable"] = true
E.db["mMT"]["afk"]["garbage"] = false
E.db["mMT"]["afk"]["logo"] = true
E.db["mMT"]["combattime"]["hide"] = 10
E.db["mMT"]["combattime"]["ictexture"] = "CI1"
E.db["mMT"]["combattime"]["ooctexture"] = "CI7"
E.db["mMT"]["dockdatatext"]["font"] = "Beep-Black"
E.db["mMT"]["dockdatatext"]["fontflag"] = "SHADOWOUTLINE"
E.db["mMT"]["general"]["keystochat"] = true
E.db["mMT"]["importantspells"]["dbversion"] = 1
E.db["mMT"]["instancedifficulty"]["enable"] = true
E.db["mMT"]["minimapAspectRatio"]["aspectRatio"] = "16:10"
E.db["mMT"]["mpscore"]["highlightcolor"]["b"] = 0.92549026012421
E.db["mMT"]["mpscore"]["highlightcolor"]["g"] = 0
E.db["mMT"]["mpscore"]["highlightcolor"]["hex"] = "|cffff00ec"
E.db["mMT"]["mpscore"]["highlightcolor"]["r"] = 1
E.db["mMT"]["mpscore"]["sort"] = "OVERA"
E.db["mMT"]["nameplate"]["bordercolor"]["border"] = true
E.db["mMT"]["nameplate"]["bordercolor"]["glow"] = true
E.db["mMT"]["nameplate"]["executemarker"]["enable"] = true
E.db["mMT"]["objectivetracker"]["convert"] = 1
E.db["mMT"]["objectivetracker"]["enable"] = true
E.db["mMT"]["objectivetracker"]["font"]["font"] = "Beep-Black"
E.db["mMT"]["objectivetracker"]["font"]["fontflag"] = "SHADOWOUTLINE"
E.db["mMT"]["objectivetracker"]["font"]["fontsize"]["time"] = 15
E.db["mMT"]["portraits"]["focus"]["enable"] = true
E.db["mMT"]["portraits"]["focus"]["mirror"] = false
E.db["mMT"]["portraits"]["focus"]["point"] = "RIGHT"
E.db["mMT"]["portraits"]["focus"]["relativePoint"] = "LEFT"
E.db["mMT"]["portraits"]["focus"]["size"] = 80
E.db["mMT"]["portraits"]["focus"]["texture"] = "octagon"
E.db["mMT"]["portraits"]["focus"]["x"] = 15
E.db["mMT"]["portraits"]["general"]["classicons"] = true
E.db["mMT"]["portraits"]["general"]["enable"] = true
E.db["mMT"]["portraits"]["general"]["style"] = "b"
E.db["mMT"]["portraits"]["party"]["texture"] = "octagon"
E.db["mMT"]["portraits"]["party"]["x"] = 16
E.db["mMT"]["portraits"]["party"]["y"] = 1
E.db["mMT"]["portraits"]["pet"]["enable"] = true
E.db["mMT"]["portraits"]["pet"]["size"] = 80
E.db["mMT"]["portraits"]["pet"]["strata"] = "HIGH"
E.db["mMT"]["portraits"]["pet"]["texture"] = "octagon"
E.db["mMT"]["portraits"]["pet"]["x"] = 14
E.db["mMT"]["portraits"]["player"]["level"] = 105
E.db["mMT"]["portraits"]["player"]["size"] = 80
E.db["mMT"]["portraits"]["player"]["texture"] = "octagon"
E.db["mMT"]["portraits"]["player"]["x"] = 15
E.db["mMT"]["portraits"]["target"]["size"] = 80
E.db["mMT"]["portraits"]["target"]["texture"] = "octagon"
E.db["mMT"]["portraits"]["target"]["x"] = -14
E.db["mMT"]["portraits"]["zoom"] = 0.7
E.db["mMT"]["roleicons"]["dd"] = "SWORD14"
E.db["mMT"]["roleicons"]["enable"] = true
E.db["mMT"]["roleicons"]["heal"] = "HEAL5"
E.db["mMT"]["teleports"]["anchorCursor"] = true
E.db["mMT"]["teleports"]["customicon"] = "TP2"
E.db["mMT"]["teleports"]["icon"] = true
E.db["mMT"]["tooltip"]["enable"] = true
E.db["mMT"]["tooltip"]["iconsize"] = 30
E.db["mMT"]["unitframeicons"]["phase"]["color"]["chromie"]["b"] = 0.37254902720451
E.db["mMT"]["unitframeicons"]["phase"]["color"]["chromie"]["g"] = 0.92549026012421
E.db["mMT"]["unitframeicons"]["phase"]["color"]["phasing"]["g"] = 0.32549020648003
E.db["mMT"]["unitframeicons"]["phase"]["color"]["phasing"]["r"] = 0.91764712333679
E.db["mMT"]["unitframeicons"]["phase"]["color"]["warmode"]["b"] = 0.3137255012989
E.db["mMT"]["unitframeicons"]["phase"]["color"]["warmode"]["g"] = 0.3137255012989
E.db["mMT"]["unitframeicons"]["phase"]["color"]["withe"] = false
E.db["mMT"]["unitframeicons"]["phase"]["enable"] = true
E.db["mMT"]["unitframeicons"]["phase"]["icon"] = "PHASE07"
E.db["mMT"]["unitframeicons"]["readycheck"]["enable"] = true
E.db["mMT"]["unitframeicons"]["readycheck"]["notready"] = "CLOSE04"
E.db["mMT"]["unitframeicons"]["readycheck"]["waiting"] = "COLOR25"
E.db["mMT"]["unitframeicons"]["resurrection"]["enable"] = true
E.db["mMT"]["unitframeicons"]["resurrection"]["icon"] = "RES01"
E.db["mMT"]["unitframeicons"]["summon"]["accepted"] = "SUM15"
E.db["mMT"]["unitframeicons"]["summon"]["available"] = "SUM13"
E.db["mMT"]["unitframeicons"]["summon"]["enable"] = true
E.db["mMT"]["unitframeicons"]["summon"]["rejected"] = "SUM14"
E.db["mMT"]["version"] = "3.68"
E.db["movers"]["AlertFrameMover"] = "TOP,UIParent,TOP,0,-175"
E.db["movers"]["AltPowerBarMover"] = "BOTTOM,UIParent,BOTTOM,0,61"
E.db["movers"]["ArenaHeaderMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-238,-297"
E.db["movers"]["ArtifactBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,99"
E.db["movers"]["AzeriteBarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-30,-183"
E.db["movers"]["BNETMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,109,157"
E.db["movers"]["BelowMinimapContainerMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-152"
E.db["movers"]["BossBannerMover"] = "TOP,UIParent,TOP,0,-142"
E.db["movers"]["BossButton"] = "BOTTOM,UIParent,BOTTOM,130,437"
E.db["movers"]["BossHeaderMover"] = "TOP,UIParent,TOP,276,-306"
E.db["movers"]["BuffsMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-155,-4"
E.db["movers"]["CM_MOVER"] = "BOTTOM,ElvUIParent,BOTTOM,0,150"
E.db["movers"]["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,329"
E.db["movers"]["ComboBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-250,313"
E.db["movers"]["DTPanelInfo PanelMover"] = "BOTTOM,UIParent,BOTTOM,0,106"
E.db["movers"]["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-157,-66"
E.db["movers"]["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,293"
E.db["movers"]["ElvAB_2"] = "BOTTOM,ElvUIParent,BOTTOM,0,263"
E.db["movers"]["ElvAB_3"] = "BOTTOM,UIParent,BOTTOM,220,464"
E.db["movers"]["ElvAB_4"] = "BOTTOM,ElvUIParent,BOTTOM,0,30"
E.db["movers"]["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,56"
E.db["movers"]["ElvAB_6"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-4,-384"
E.db["movers"]["ElvUF_AssistMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,30,-340"
E.db["movers"]["ElvUF_FocusCastbarMover"] = "BOTTOM,UIParent,BOTTOM,0,361"
E.db["movers"]["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,374"
E.db["movers"]["ElvUF_PartyMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,396,391"
E.db["movers"]["ElvUF_PetCastbarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,573,343"
E.db["movers"]["ElvUF_PetMover"] = "BOTTOM,ElvUIParent,BOTTOM,-233,259"
E.db["movers"]["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-234,297"
E.db["movers"]["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-234,310"
E.db["movers"]["ElvUF_Raid1Mover"] = "BOTTOM,UIParent,BOTTOM,0,48"
E.db["movers"]["ElvUF_Raid2Mover"] = "BOTTOM,UIParent,BOTTOM,0,49"
E.db["movers"]["ElvUF_Raid3Mover"] = "BOTTOM,UIParent,BOTTOM,0,47"
E.db["movers"]["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,736"
E.db["movers"]["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,234,298"
E.db["movers"]["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,234,311"
E.db["movers"]["ElvUF_TargetTargetMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-541,345"
E.db["movers"]["ElvUIBankMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,4,143"
E.db["movers"]["EventToastMover"] = "TOP,UIParent,TOP,0,-68"
E.db["movers"]["ExperienceBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,0"
E.db["movers"]["FocusPowerBarMover"] = "BOTTOM,UIParent,BOTTOM,0,362"
E.db["movers"]["GMMover"] = "TOPLEFT,UIParent,TOPLEFT,4,-4"
E.db["movers"]["GhostFrameMover"] = "TOP,ElvUIParent,TOP,0,-147"
E.db["movers"]["HonorBarMover"] = "TOP,ElvUIParent,TOP,0,-66"
E.db["movers"]["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,4,23"
E.db["movers"]["LootFrameMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-208,64"
E.db["movers"]["LossControlMover"] = "TOP,UIParent,TOP,0,-508"
E.db["movers"]["MicrobarMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,30,-30"
E.db["movers"]["MinimapMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-4,-4"
E.db["movers"]["ObjectiveFrameMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-21,-157"
E.db["movers"]["PetAB"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-115,11"
E.db["movers"]["PlayerPowerBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,329"
E.db["movers"]["PowerBarContainerMover"] = "TOP,UIParent,TOP,0,-96"
E.db["movers"]["PrivateRaidWarningMover"] = "TOP,UIParent,TOP,0,-208"
E.db["movers"]["QueueStatusMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-126,-126"
E.db["movers"]["ReputationBarMover"] = "TOP,ElvUIParent,TOP,0,-33"
E.db["movers"]["RightChatMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,4"
E.db["movers"]["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,0,244"
E.db["movers"]["TalkingHeadFrameMover"] = "TOP,ElvUIParent,TOP,0,-4"
E.db["movers"]["TargetPowerBarMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-399,224"
E.db["movers"]["ThreatBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,339"
E.db["movers"]["TooltipMover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-195,4"
E.db["movers"]["TopCenterContainerMover"] = "TOP,UIParent,TOP,0,-86"
E.db["movers"]["TorghastChoiceToggle"] = "BOTTOM,ElvUIParent,BOTTOM,0,429"
E.db["movers"]["TotemBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-182,325"
E.db["movers"]["TotemTrackerMover"] = "BOTTOM,UIParent,BOTTOM,0,141"
E.db["movers"]["VOICECHAT"] = "TOPLEFT,UIParent,TOPLEFT,4,-83"
E.db["movers"]["VehicleLeaveButton"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,460,292"
E.db["movers"]["VehicleSeatMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,30,-410"
E.db["movers"]["WTCombatAlertFrameMover"] = "TOP,ElvUIParent,TOP,0,-317"
E.db["movers"]["WTCustomEmoteFrameMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,337,4"
E.db["movers"]["WTExtraItemsBar1Mover"] = "BOTTOMRIGHT,UIParent,BOTTOMRIGHT,-4,117"
E.db["movers"]["WTGameBarAnchor"] = "TOP,UIParent,TOP,0,-84"
E.db["movers"]["WTSwitchButtonBarMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-45,-278"
E.db["movers"]["WatchFrameMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-30,-300"
E.db["movers"]["ZoneAbility"] = "BOTTOM,UIParent,BOTTOM,130,411"
E.db["nameplates"]["colors"]["glowColor"]["b"] = 0.22745099663734
E.db["nameplates"]["colors"]["glowColor"]["g"] = 0.11764706671238
E.db["nameplates"]["colors"]["glowColor"]["r"] = 0.76862752437592
E.db["nameplates"]["cooldown"]["fonts"]["font"] = "Beep-Black"
E.db["nameplates"]["cooldown"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["cooldown"]["fonts"]["fontSize"] = 11
E.db["nameplates"]["font"] = "Expressway"
E.db["nameplates"]["loadDistance"] = 65
E.db["nameplates"]["lowHealthThreshold"] = 0
E.db["nameplates"]["motionType"] = "OVERLAP"
E.db["nameplates"]["statusbar"] = "ElvUI Norm1"
E.db["nameplates"]["units"]["ENEMY_NPC"]["buffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["castbar"]["castTimeFormat"] = "REMAINING"
E.db["nameplates"]["units"]["ENEMY_NPC"]["castbar"]["channelTimeFormat"] = "REMAINING"
E.db["nameplates"]["units"]["ENEMY_NPC"]["castbar"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["castbar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["debuffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["health"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["health"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["level"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["level"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["name"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["name"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["power"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["power"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["questIcon"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["questIcon"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_NPC"]["title"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_NPC"]["title"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["buffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["castbar"]["castTimeFormat"] = "REMAINING"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["castbar"]["channelTimeFormat"] = "REMAINING"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["castbar"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["castbar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["debuffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["health"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["health"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["level"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["level"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["name"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["name"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["power"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["power"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["title"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["ENEMY_PLAYER"]["title"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["buffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["castbar"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["castbar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["debuffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["health"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["health"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["level"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["level"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["name"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["name"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["power"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["power"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["questIcon"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["questIcon"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["title"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_NPC"]["title"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["buffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["castbar"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["castbar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["debuffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["health"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["health"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["level"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["level"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["name"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["name"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["power"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["power"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["title"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["FRIENDLY_PLAYER"]["title"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["buffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["castbar"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["castbar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["debuffs"]["countFont"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["health"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["health"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["level"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["level"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["name"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["name"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["power"]["text"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["power"]["text"]["fontOutline"] = "SHADOWOUTLINE"
E.db["nameplates"]["units"]["PLAYER"]["title"]["font"] = "Beep-Black"
E.db["nameplates"]["units"]["PLAYER"]["title"]["fontOutline"] = "SHADOWOUTLINE"
E.db["tooltip"]["colorAlpha"] = 0.9
E.db["tooltip"]["font"] = "Beep-Black"
E.db["tooltip"]["fontOutline"] = "SHADOWOUTLINE"
E.db["tooltip"]["guildRanks"] = false
E.db["tooltip"]["headerFont"] = "Beep-Black"
E.db["tooltip"]["headerFontOutline"] = "SHADOWOUTLINE"
E.db["tooltip"]["headerFontSize"] = 11
E.db["tooltip"]["healthBar"]["font"] = "Beep-Black"
E.db["tooltip"]["healthBar"]["fontOutline"] = "SHADOWOUTLINE"
E.db["tooltip"]["healthBar"]["height"] = 0
E.db["tooltip"]["healthBar"]["text"] = false
E.db["tooltip"]["itemCount"]["bank"] = true
E.db["tooltip"]["playerTitles"] = false
E.db["tooltip"]["smallTextFontSize"] = 11
E.db["tooltip"]["textFontSize"] = 11
E.db["unitframe"]["colors"]["castColor"]["b"] = 0.8
E.db["unitframe"]["colors"]["castColor"]["g"] = 0.8
E.db["unitframe"]["colors"]["castColor"]["r"] = 0.8
E.db["unitframe"]["colors"]["castNoInterrupt"]["b"] = 0.23921568627451
E.db["unitframe"]["colors"]["castNoInterrupt"]["g"] = 0.19607843137255
E.db["unitframe"]["colors"]["castNoInterrupt"]["r"] = 0.91372549019608
E.db["unitframe"]["colors"]["classResources"]["MONK"][1]["b"] = 0.58823529411765
E.db["unitframe"]["colors"]["classResources"]["MONK"][1]["g"] = 1
E.db["unitframe"]["colors"]["classResources"]["MONK"][1]["r"] = 0
E.db["unitframe"]["colors"]["classResources"]["MONK"][2]["b"] = 0.58823529411765
E.db["unitframe"]["colors"]["classResources"]["MONK"][2]["g"] = 1
E.db["unitframe"]["colors"]["classResources"]["MONK"][2]["r"] = 0
E.db["unitframe"]["colors"]["classResources"]["MONK"][3]["b"] = 0.58823529411765
E.db["unitframe"]["colors"]["classResources"]["MONK"][3]["g"] = 1
E.db["unitframe"]["colors"]["classResources"]["MONK"][3]["r"] = 0
E.db["unitframe"]["colors"]["classResources"]["MONK"][4]["b"] = 0.58823529411765
E.db["unitframe"]["colors"]["classResources"]["MONK"][4]["g"] = 1
E.db["unitframe"]["colors"]["classResources"]["MONK"][4]["r"] = 0
E.db["unitframe"]["colors"]["classResources"]["MONK"][5]["b"] = 0.58823529411765
E.db["unitframe"]["colors"]["classResources"]["MONK"][5]["g"] = 1
E.db["unitframe"]["colors"]["classResources"]["MONK"][5]["r"] = 0
E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["b"] = 0.58823529411765
E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["g"] = 1
E.db["unitframe"]["colors"]["classResources"]["MONK"][6]["r"] = 0
E.db["unitframe"]["colors"]["colorhealthbyvalue"] = false
E.db["unitframe"]["colors"]["customhealthbackdrop"] = true
E.db["unitframe"]["colors"]["disconnected"]["b"] = 0.85098039215686
E.db["unitframe"]["colors"]["disconnected"]["g"] = 0.7921568627451
E.db["unitframe"]["colors"]["disconnected"]["r"] = 0.76470588235294
E.db["unitframe"]["colors"]["frameGlow"]["mainGlow"]["enable"] = true
E.db["unitframe"]["colors"]["frameGlow"]["mouseoverGlow"]["color"]["a"] = 0.35993927717209
E.db["unitframe"]["colors"]["frameGlow"]["mouseoverGlow"]["color"]["b"] = 0
E.db["unitframe"]["colors"]["frameGlow"]["mouseoverGlow"]["color"]["g"] = 0
E.db["unitframe"]["colors"]["frameGlow"]["mouseoverGlow"]["color"]["r"] = 0
E.db["unitframe"]["colors"]["frameGlow"]["mouseoverGlow"]["enable"] = false
E.db["unitframe"]["colors"]["frameGlow"]["targetGlow"]["color"]["r"] = 0.95294123888016
E.db["unitframe"]["colors"]["health"]["b"] = 0.40392156862745
E.db["unitframe"]["colors"]["health"]["g"] = 1
E.db["unitframe"]["colors"]["health"]["r"] = 0.41960784313726
E.db["unitframe"]["colors"]["health_backdrop"]["b"] = 0.070588235294118
E.db["unitframe"]["colors"]["health_backdrop"]["g"] = 0.070588235294118
E.db["unitframe"]["colors"]["health_backdrop"]["r"] = 0.070588235294118
E.db["unitframe"]["colors"]["healthclass"] = true
E.db["unitframe"]["colors"]["power"]["ENERGY"]["b"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["ENERGY"]["g"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["ENERGY"]["r"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["FOCUS"]["b"] = 0.23529411764706
E.db["unitframe"]["colors"]["power"]["FOCUS"]["g"] = 0.54901960784314
E.db["unitframe"]["colors"]["power"]["FOCUS"]["r"] = 0.90196078431373
E.db["unitframe"]["colors"]["power"]["MANA"]["b"] = 0.90196078431373
E.db["unitframe"]["colors"]["power"]["MANA"]["g"] = 0.74509803921569
E.db["unitframe"]["colors"]["power"]["MANA"]["r"] = 0
E.db["unitframe"]["colors"]["power"]["RAGE"]["b"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["RAGE"]["g"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["RAGE"]["r"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["RUNIC_POWER"]["b"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["RUNIC_POWER"]["g"] = 0.27450980392157
E.db["unitframe"]["colors"]["power"]["RUNIC_POWER"]["r"] = 0.27450980392157
E.db["unitframe"]["colors"]["reaction"]["BAD"]["b"] = 0.25098039215686
E.db["unitframe"]["colors"]["reaction"]["BAD"]["g"] = 0.25098039215686
E.db["unitframe"]["colors"]["reaction"]["BAD"]["r"] = 0.78039215686274
E.db["unitframe"]["colors"]["tapped"]["b"] = 0.85098039215686
E.db["unitframe"]["colors"]["tapped"]["g"] = 0.7921568627451
E.db["unitframe"]["colors"]["tapped"]["r"] = 0.76470588235294
E.db["unitframe"]["cooldown"]["fonts"]["font"] = "Beep-Black"
E.db["unitframe"]["cooldown"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["debuffHighlighting"] = "NONE"
E.db["unitframe"]["font"] = "Beep-Black"
E.db["unitframe"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["fontSize"] = 11
E.db["unitframe"]["statusbar"] = "ElvUI Norm1"
E.db["unitframe"]["units"]["arena"]["buffs"]["anchorPoint"] = "RIGHT"
E.db["unitframe"]["units"]["arena"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["arena"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["arena"]["buffs"]["sizeOverride"] = 18
E.db["unitframe"]["units"]["arena"]["buffs"]["xOffset"] = 2
E.db["unitframe"]["units"]["arena"]["buffs"]["yOffset"] = 10
E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["arena"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["arena"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["arena"]["castbar"]["format"] = ""
E.db["unitframe"]["units"]["arena"]["castbar"]["height"] = 10
E.db["unitframe"]["units"]["arena"]["castbar"]["icon"] = false
E.db["unitframe"]["units"]["arena"]["castbar"]["spark"] = false
E.db["unitframe"]["units"]["arena"]["castbar"]["width"] = 225
E.db["unitframe"]["units"]["arena"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["arena"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["arena"]["debuffs"]["sizeOverride"] = 18
E.db["unitframe"]["units"]["arena"]["debuffs"]["xOffset"] = 2
E.db["unitframe"]["units"]["arena"]["debuffs"]["yOffset"] = -10
E.db["unitframe"]["units"]["arena"]["enable"] = false
E.db["unitframe"]["units"]["arena"]["health"]["text_format"] = "[health:current]"
E.db["unitframe"]["units"]["arena"]["height"] = 40
E.db["unitframe"]["units"]["arena"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["arena"]["power"]["height"] = 3
E.db["unitframe"]["units"]["arena"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["arena"]["width"] = 225
E.db["unitframe"]["units"]["assist"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["assist"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["assist"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["assist"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["assist"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["assist"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["assist"]["enable"] = false
E.db["unitframe"]["units"]["assist"]["rdebuffs"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["assist"]["rdebuffs"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["boss"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["boss"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["boss"]["buffs"]["sizeOverride"] = 30
E.db["unitframe"]["units"]["boss"]["buffs"]["xOffset"] = -1
E.db["unitframe"]["units"]["boss"]["buffs"]["yOffset"] = 0
E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["boss"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["boss"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["boss"]["castbar"]["height"] = 24
E.db["unitframe"]["units"]["boss"]["castbar"]["icon"] = false
E.db["unitframe"]["units"]["boss"]["castbar"]["spark"] = false
E.db["unitframe"]["units"]["boss"]["castbar"]["width"] = 184
E.db["unitframe"]["units"]["boss"]["debuffs"]["anchorPoint"] = "RIGHT"
E.db["unitframe"]["units"]["boss"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["boss"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["boss"]["debuffs"]["enable"] = false
E.db["unitframe"]["units"]["boss"]["debuffs"]["sizeOverride"] = 35
E.db["unitframe"]["units"]["boss"]["debuffs"]["xOffset"] = 3
E.db["unitframe"]["units"]["boss"]["debuffs"]["yOffset"] = 0
E.db["unitframe"]["units"]["boss"]["enable"] = false
E.db["unitframe"]["units"]["boss"]["growthDirection"] = "UP"
E.db["unitframe"]["units"]["boss"]["health"]["position"] = "TOPRIGHT"
E.db["unitframe"]["units"]["boss"]["health"]["text_format"] = "[perhp]%"
E.db["unitframe"]["units"]["boss"]["health"]["yOffset"] = -2
E.db["unitframe"]["units"]["boss"]["height"] = 30
E.db["unitframe"]["units"]["boss"]["name"]["position"] = "LEFT"
E.db["unitframe"]["units"]["boss"]["name"]["text_format"] = "[name]"
E.db["unitframe"]["units"]["boss"]["name"]["xOffset"] = 2
E.db["unitframe"]["units"]["boss"]["power"]["height"] = 3
E.db["unitframe"]["units"]["boss"]["power"]["position"] = "BOTTOMRIGHT"
E.db["unitframe"]["units"]["boss"]["power"]["text_format"] = "[power:current]"
E.db["unitframe"]["units"]["boss"]["power"]["xOffset"] = 2
E.db["unitframe"]["units"]["boss"]["spacing"] = 30
E.db["unitframe"]["units"]["boss"]["width"] = 184
E.db["unitframe"]["units"]["focus"]["aurabar"]["anchorPoint"] = "Below"
E.db["unitframe"]["units"]["focus"]["aurabar"]["attachTo"] = "Debuffs"
E.db["unitframe"]["units"]["focus"]["aurabar"]["detachedWidth"] = 270
E.db["unitframe"]["units"]["focus"]["aurabar"]["maxBars"] = 6
E.db["unitframe"]["units"]["focus"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["buffs"]["growthX"] = "LEFT"
E.db["unitframe"]["units"]["focus"]["buffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["focus"]["buffs"]["perrow"] = 8
E.db["unitframe"]["units"]["focus"]["buffs"]["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,nonPersonal"
E.db["unitframe"]["units"]["focus"]["buffs"]["yOffset"] = -1
E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontSize"] = 10
E.db["unitframe"]["units"]["focus"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["castbar"]["height"] = 14
E.db["unitframe"]["units"]["focus"]["castbar"]["icon"] = false
E.db["unitframe"]["units"]["focus"]["castbar"]["spark"] = false
E.db["unitframe"]["units"]["focus"]["castbar"]["width"] = 101
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["enable"] = true
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["size"] = 11
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["text_format"] = "[health:percent]"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["xOffset"] = 0
E.db["unitframe"]["units"]["focus"]["customTexts"]["Health %"]["yOffset"] = 0
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["enable"] = true
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["size"] = 11
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["text_format"] = "[power:percent]"
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["xOffset"] = 0
E.db["unitframe"]["units"]["focus"]["customTexts"]["Power %"]["yOffset"] = 0
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["enable"] = true
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["justifyH"] = "CENTER"
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["size"] = 11
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["text_format"] = "[level]"
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["xOffset"] = 43
E.db["unitframe"]["units"]["focus"]["customTexts"]["[level]"]["yOffset"] = 12
E.db["unitframe"]["units"]["focus"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["focus"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["focus"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focus"]["debuffs"]["enable"] = false
E.db["unitframe"]["units"]["focus"]["debuffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["focus"]["debuffs"]["perrow"] = 8
E.db["unitframe"]["units"]["focus"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
E.db["unitframe"]["units"]["focus"]["debuffs"]["yOffset"] = -16
E.db["unitframe"]["units"]["focus"]["disableTargetGlow"] = true
E.db["unitframe"]["units"]["focus"]["fader"]["enable"] = false
E.db["unitframe"]["units"]["focus"]["fader"]["range"] = false
E.db["unitframe"]["units"]["focus"]["healPrediction"]["enable"] = false
E.db["unitframe"]["units"]["focus"]["health"]["position"] = "LEFT"
E.db["unitframe"]["units"]["focus"]["health"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["focus"]["health"]["xOffset"] = 2
E.db["unitframe"]["units"]["focus"]["height"] = 24
E.db["unitframe"]["units"]["focus"]["infoPanel"]["height"] = 20
E.db["unitframe"]["units"]["focus"]["name"]["position"] = "TOPLEFT"
E.db["unitframe"]["units"]["focus"]["name"]["text_format"] = "[name:long]"
E.db["unitframe"]["units"]["focus"]["name"]["yOffset"] = 12
E.db["unitframe"]["units"]["focus"]["orientation"] = "RIGHT"
E.db["unitframe"]["units"]["focus"]["power"]["detachedWidth"] = 301
E.db["unitframe"]["units"]["focus"]["power"]["height"] = 12
E.db["unitframe"]["units"]["focus"]["power"]["powerPrediction"] = true
E.db["unitframe"]["units"]["focus"]["power"]["text_format"] = "[power:current:shortvalue]"
E.db["unitframe"]["units"]["focus"]["power"]["yOffset"] = -11
E.db["unitframe"]["units"]["focus"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["focus"]["width"] = 101
E.db["unitframe"]["units"]["focustarget"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["focustarget"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focustarget"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["focustarget"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["focustarget"]["power"]["height"] = 3
E.db["unitframe"]["units"]["party"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["buffIndicator"]["size"] = 7
E.db["unitframe"]["units"]["party"]["buffs"]["anchorPoint"] = "RIGHT"
E.db["unitframe"]["units"]["party"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["buffs"]["perrow"] = 2
E.db["unitframe"]["units"]["party"]["buffs"]["sizeOverride"] = 20
E.db["unitframe"]["units"]["party"]["buffs"]["xOffset"] = -47
E.db["unitframe"]["units"]["party"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["enable"] = true
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["size"] = 24
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["text_format"] = "[mStatus:icon]"
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["xOffset"] = -101
E.db["unitframe"]["units"]["party"]["customTexts"]["Status"]["yOffset"] = -6
E.db["unitframe"]["units"]["party"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["debuffs"]["countFontSize"] = 11
E.db["unitframe"]["units"]["party"]["debuffs"]["perrow"] = 2
E.db["unitframe"]["units"]["party"]["debuffs"]["sizeOverride"] = 20
E.db["unitframe"]["units"]["party"]["debuffs"]["xOffset"] = 1
E.db["unitframe"]["units"]["party"]["growthDirection"] = "DOWN_RIGHT"
E.db["unitframe"]["units"]["party"]["healPrediction"]["enable"] = true
E.db["unitframe"]["units"]["party"]["health"]["position"] = "CENTER"
E.db["unitframe"]["units"]["party"]["health"]["text_format"] = "[health:percent]"
E.db["unitframe"]["units"]["party"]["height"] = 28
E.db["unitframe"]["units"]["party"]["horizontalSpacing"] = -5
E.db["unitframe"]["units"]["party"]["name"]["text_format"] = "[name:long]"
E.db["unitframe"]["units"]["party"]["name"]["yOffset"] = 13
E.db["unitframe"]["units"]["party"]["petsGroup"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["petsGroup"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["power"]["height"] = 14
E.db["unitframe"]["units"]["party"]["power"]["text_format"] = ""
E.db["unitframe"]["units"]["party"]["privateAuras"]["enable"] = false
E.db["unitframe"]["units"]["party"]["raidRoleIcons"]["yOffset"] = 5
E.db["unitframe"]["units"]["party"]["rdebuffs"]["enable"] = false
E.db["unitframe"]["units"]["party"]["rdebuffs"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["party"]["rdebuffs"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["party"]["roleIcon"]["position"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["party"]["threatStyle"] = "BORDERS"
E.db["unitframe"]["units"]["party"]["verticalSpacing"] = 31
E.db["unitframe"]["units"]["party"]["width"] = 110
E.db["unitframe"]["units"]["pet"]["aurabar"]["anchorPoint"] = "Below"
E.db["unitframe"]["units"]["pet"]["aurabar"]["attachTo"] = "Debuffs"
E.db["unitframe"]["units"]["pet"]["aurabar"]["detachedWidth"] = 270
E.db["unitframe"]["units"]["pet"]["aurabar"]["priority"] = "Blacklist,blockNoDuration,Personal,RaidDebuffs"
E.db["unitframe"]["units"]["pet"]["aurabar"]["spacing"] = 0
E.db["unitframe"]["units"]["pet"]["aurabar"]["yOffset"] = 0
E.db["unitframe"]["units"]["pet"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["buffs"]["growthX"] = "LEFT"
E.db["unitframe"]["units"]["pet"]["buffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["pet"]["buffs"]["perrow"] = 8
E.db["unitframe"]["units"]["pet"]["buffs"]["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,nonPersonal"
E.db["unitframe"]["units"]["pet"]["buffs"]["yOffset"] = -1
E.db["unitframe"]["units"]["pet"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["castbar"]["customTextFont"]["fontSize"] = 10
E.db["unitframe"]["units"]["pet"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["castbar"]["height"] = 14
E.db["unitframe"]["units"]["pet"]["castbar"]["icon"] = false
E.db["unitframe"]["units"]["pet"]["castbar"]["spark"] = false
E.db["unitframe"]["units"]["pet"]["castbar"]["width"] = 101
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["enable"] = true
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["size"] = 11
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["text_format"] = "[health:percent]"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["xOffset"] = 0
E.db["unitframe"]["units"]["pet"]["customTexts"]["Health %"]["yOffset"] = 0
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["enable"] = true
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["size"] = 11
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["text_format"] = "[power:percent]"
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["xOffset"] = 0
E.db["unitframe"]["units"]["pet"]["customTexts"]["Power %"]["yOffset"] = 0
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["enable"] = true
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["justifyH"] = "CENTER"
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["size"] = 11
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["text_format"] = "[level]"
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["xOffset"] = 43
E.db["unitframe"]["units"]["pet"]["customTexts"]["[level]"]["yOffset"] = 12
E.db["unitframe"]["units"]["pet"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["pet"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["pet"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pet"]["debuffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["pet"]["debuffs"]["perrow"] = 8
E.db["unitframe"]["units"]["pet"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
E.db["unitframe"]["units"]["pet"]["debuffs"]["yOffset"] = -16
E.db["unitframe"]["units"]["pet"]["fader"]["enable"] = false
E.db["unitframe"]["units"]["pet"]["fader"]["range"] = false
E.db["unitframe"]["units"]["pet"]["healPrediction"]["enable"] = false
E.db["unitframe"]["units"]["pet"]["health"]["position"] = "LEFT"
E.db["unitframe"]["units"]["pet"]["health"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["pet"]["health"]["xOffset"] = 2
E.db["unitframe"]["units"]["pet"]["height"] = 24
E.db["unitframe"]["units"]["pet"]["infoPanel"]["height"] = 20
E.db["unitframe"]["units"]["pet"]["name"]["position"] = "TOPLEFT"
E.db["unitframe"]["units"]["pet"]["name"]["text_format"] = "[name:long]"
E.db["unitframe"]["units"]["pet"]["name"]["yOffset"] = 12
E.db["unitframe"]["units"]["pet"]["orientation"] = "RIGHT"
E.db["unitframe"]["units"]["pet"]["power"]["detachedWidth"] = 301
E.db["unitframe"]["units"]["pet"]["power"]["height"] = 12
E.db["unitframe"]["units"]["pet"]["power"]["powerPrediction"] = true
E.db["unitframe"]["units"]["pet"]["power"]["text_format"] = "[power:current:shortvalue]"
E.db["unitframe"]["units"]["pet"]["power"]["yOffset"] = -11
E.db["unitframe"]["units"]["pet"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["pet"]["width"] = 101
E.db["unitframe"]["units"]["pettarget"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["pettarget"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pettarget"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["pettarget"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["pettarget"]["power"]["height"] = 3
E.db["unitframe"]["units"]["player"]["RestIcon"]["enable"] = false
E.db["unitframe"]["units"]["player"]["aurabar"]["anchorPoint"] = "Below"
E.db["unitframe"]["units"]["player"]["aurabar"]["attachTo"] = "Debuffs"
E.db["unitframe"]["units"]["player"]["aurabar"]["enable"] = false
E.db["unitframe"]["units"]["player"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["buffs"]["anchorPoint"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["player"]["buffs"]["attachTo"] = "FRAME"
E.db["unitframe"]["units"]["player"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["buffs"]["growthX"] = "LEFT"
E.db["unitframe"]["units"]["player"]["buffs"]["yOffset"] = -1
E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["fontSize"] = 10
E.db["unitframe"]["units"]["player"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["castbar"]["height"] = 14
E.db["unitframe"]["units"]["player"]["castbar"]["icon"] = false
E.db["unitframe"]["units"]["player"]["castbar"]["latency"] = false
E.db["unitframe"]["units"]["player"]["castbar"]["spark"] = false
E.db["unitframe"]["units"]["player"]["castbar"]["width"] = 101
E.db["unitframe"]["units"]["player"]["classbar"]["detachFromFrame"] = true
E.db["unitframe"]["units"]["player"]["classbar"]["detachedWidth"] = 301
E.db["unitframe"]["units"]["player"]["classbar"]["height"] = 8
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["size"] = 11
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["text_format"] = "[health:percent]"
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["xOffset"] = 0
E.db["unitframe"]["units"]["player"]["customTexts"]["Health %"]["yOffset"] = 0
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["size"] = 11
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["text_format"] = "[power:percent]"
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["xOffset"] = 0
E.db["unitframe"]["units"]["player"]["customTexts"]["Power %"]["yOffset"] = 0
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["enable"] = true
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["justifyH"] = "CENTER"
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["size"] = 11
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["text_format"] = "[level]"
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["xOffset"] = 43
E.db["unitframe"]["units"]["player"]["customTexts"]["[level]"]["yOffset"] = 12
E.db["unitframe"]["units"]["player"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["player"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["player"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["player"]["debuffs"]["enable"] = false
E.db["unitframe"]["units"]["player"]["debuffs"]["growthX"] = "LEFT"
E.db["unitframe"]["units"]["player"]["debuffs"]["yOffset"] = -16
E.db["unitframe"]["units"]["player"]["healPrediction"]["enable"] = false
E.db["unitframe"]["units"]["player"]["health"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["player"]["height"] = 24
E.db["unitframe"]["units"]["player"]["name"]["position"] = "TOPLEFT"
E.db["unitframe"]["units"]["player"]["name"]["text_format"] = "[name:long]"
E.db["unitframe"]["units"]["player"]["name"]["yOffset"] = 12
E.db["unitframe"]["units"]["player"]["orientation"] = "RIGHT"
E.db["unitframe"]["units"]["player"]["power"]["detachedWidth"] = 301
E.db["unitframe"]["units"]["player"]["power"]["height"] = 12
E.db["unitframe"]["units"]["player"]["power"]["position"] = "LEFT"
E.db["unitframe"]["units"]["player"]["power"]["powerPrediction"] = true
E.db["unitframe"]["units"]["player"]["power"]["text_format"] = "[power:current:shortvalue]"
E.db["unitframe"]["units"]["player"]["power"]["xOffset"] = 2
E.db["unitframe"]["units"]["player"]["power"]["yOffset"] = -11
E.db["unitframe"]["units"]["player"]["pvp"]["text_format"] = ""
E.db["unitframe"]["units"]["player"]["raidRoleIcons"]["enable"] = false
E.db["unitframe"]["units"]["player"]["stagger"]["enable"] = false
E.db["unitframe"]["units"]["player"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["player"]["width"] = 101
E.db["unitframe"]["units"]["raid1"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid1"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid1"]["buffIndicator"]["enable"] = false
E.db["unitframe"]["units"]["raid1"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid1"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid1"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid1"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid1"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["raid1"]["height"] = 23
E.db["unitframe"]["units"]["raid1"]["horizontalSpacing"] = 1
E.db["unitframe"]["units"]["raid1"]["name"]["position"] = "TOP"
E.db["unitframe"]["units"]["raid1"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["raid1"]["name"]["yOffset"] = -4
E.db["unitframe"]["units"]["raid1"]["numGroups"] = 8
E.db["unitframe"]["units"]["raid1"]["power"]["enable"] = false
E.db["unitframe"]["units"]["raid1"]["power"]["height"] = 3
E.db["unitframe"]["units"]["raid1"]["raidRoleIcons"]["enable"] = false
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["fontSize"] = 11
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["size"] = 16
E.db["unitframe"]["units"]["raid1"]["rdebuffs"]["yOffset"] = 1
E.db["unitframe"]["units"]["raid1"]["roleIcon"]["enable"] = false
E.db["unitframe"]["units"]["raid1"]["threatStyle"] = "BORDERS"
E.db["unitframe"]["units"]["raid1"]["verticalSpacing"] = 1
E.db["unitframe"]["units"]["raid1"]["width"] = 64
E.db["unitframe"]["units"]["raid2"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid2"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid2"]["buffIndicator"]["enable"] = false
E.db["unitframe"]["units"]["raid2"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid2"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid2"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid2"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid2"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["raid2"]["height"] = 23
E.db["unitframe"]["units"]["raid2"]["horizontalSpacing"] = 1
E.db["unitframe"]["units"]["raid2"]["name"]["position"] = "TOP"
E.db["unitframe"]["units"]["raid2"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["raid2"]["name"]["yOffset"] = -4
E.db["unitframe"]["units"]["raid2"]["numGroups"] = 8
E.db["unitframe"]["units"]["raid2"]["power"]["height"] = 3
E.db["unitframe"]["units"]["raid2"]["raidRoleIcons"]["enable"] = false
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["enable"] = true
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["fontSize"] = 11
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["size"] = 16
E.db["unitframe"]["units"]["raid2"]["rdebuffs"]["yOffset"] = 1
E.db["unitframe"]["units"]["raid2"]["threatStyle"] = "BORDERS"
E.db["unitframe"]["units"]["raid2"]["verticalSpacing"] = 1
E.db["unitframe"]["units"]["raid2"]["width"] = 64
E.db["unitframe"]["units"]["raid3"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid3"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid3"]["buffIndicator"]["enable"] = false
E.db["unitframe"]["units"]["raid3"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid3"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid3"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raid3"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid3"]["health"]["text_format"] = ""
E.db["unitframe"]["units"]["raid3"]["height"] = 23
E.db["unitframe"]["units"]["raid3"]["horizontalSpacing"] = 1
E.db["unitframe"]["units"]["raid3"]["name"]["position"] = "TOP"
E.db["unitframe"]["units"]["raid3"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["raid3"]["name"]["yOffset"] = -4
E.db["unitframe"]["units"]["raid3"]["power"]["height"] = 3
E.db["unitframe"]["units"]["raid3"]["raidRoleIcons"]["enable"] = false
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["enable"] = true
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["fontSize"] = 11
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["size"] = 16
E.db["unitframe"]["units"]["raid3"]["rdebuffs"]["yOffset"] = 1
E.db["unitframe"]["units"]["raid3"]["threatStyle"] = "BORDERS"
E.db["unitframe"]["units"]["raid3"]["verticalSpacing"] = 1
E.db["unitframe"]["units"]["raid3"]["width"] = 64
E.db["unitframe"]["units"]["raidpet"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raidpet"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raidpet"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raidpet"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["raidpet"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["raidpet"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["tank"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["tank"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["tank"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["tank"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["tank"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["tank"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["tank"]["enable"] = false
E.db["unitframe"]["units"]["tank"]["rdebuffs"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["tank"]["rdebuffs"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["aurabar"]["anchorPoint"] = "Below"
E.db["unitframe"]["units"]["target"]["aurabar"]["attachTo"] = "Debuffs"
E.db["unitframe"]["units"]["target"]["aurabar"]["enable"] = false
E.db["unitframe"]["units"]["target"]["buffIndicator"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["buffIndicator"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["buffs"]["anchorPoint"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["target"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["buffs"]["enable"] = false
E.db["unitframe"]["units"]["target"]["buffs"]["priority"] = "Blacklist,Whitelist,blockNoDuration,Personal,nonPersonal"
E.db["unitframe"]["units"]["target"]["buffs"]["yOffset"] = -1
E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontSize"] = 10
E.db["unitframe"]["units"]["target"]["castbar"]["customTextFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["castbar"]["customTimeFont"]["fontStyle"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["castbar"]["height"] = 14
E.db["unitframe"]["units"]["target"]["castbar"]["icon"] = false
E.db["unitframe"]["units"]["target"]["castbar"]["spark"] = false
E.db["unitframe"]["units"]["target"]["castbar"]["width"] = 101
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["size"] = 11
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["text_format"] = "[health:percent]"
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["xOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["Health %"]["yOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["attachTextTo"] = "Power"
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["justifyH"] = "RIGHT"
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["size"] = 11
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["text_format"] = "[power:percent]"
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["xOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["Power %"]["yOffset"] = 0
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["attachTextTo"] = "Health"
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["enable"] = true
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["font"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["fontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["justifyH"] = "CENTER"
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["size"] = 11
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["text_format"] = "[level]"
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["xOffset"] = 43
E.db["unitframe"]["units"]["target"]["customTexts"]["[level]"]["yOffset"] = 12
E.db["unitframe"]["units"]["target"]["debuffs"]["anchorPoint"] = "BOTTOMLEFT"
E.db["unitframe"]["units"]["target"]["debuffs"]["attachTo"] = "FRAME"
E.db["unitframe"]["units"]["target"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["target"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["target"]["debuffs"]["enable"] = false
E.db["unitframe"]["units"]["target"]["debuffs"]["maxDuration"] = 0
E.db["unitframe"]["units"]["target"]["debuffs"]["priority"] = "Blacklist,Personal,nonPersonal"
E.db["unitframe"]["units"]["target"]["debuffs"]["yOffset"] = -16
E.db["unitframe"]["units"]["target"]["fader"]["enable"] = false
E.db["unitframe"]["units"]["target"]["fader"]["range"] = false
E.db["unitframe"]["units"]["target"]["healPrediction"]["enable"] = false
E.db["unitframe"]["units"]["target"]["health"]["position"] = "LEFT"
E.db["unitframe"]["units"]["target"]["health"]["text_format"] = "[health:current:shortvalue]"
E.db["unitframe"]["units"]["target"]["health"]["xOffset"] = 2
E.db["unitframe"]["units"]["target"]["height"] = 24
E.db["unitframe"]["units"]["target"]["name"]["position"] = "TOPLEFT"
E.db["unitframe"]["units"]["target"]["name"]["text_format"] = "[name:long]"
E.db["unitframe"]["units"]["target"]["name"]["yOffset"] = 12
E.db["unitframe"]["units"]["target"]["power"]["detachedWidth"] = 301
E.db["unitframe"]["units"]["target"]["power"]["height"] = 12
E.db["unitframe"]["units"]["target"]["power"]["powerPrediction"] = true
E.db["unitframe"]["units"]["target"]["power"]["text_format"] = "[power:current:shortvalue]"
E.db["unitframe"]["units"]["target"]["power"]["yOffset"] = -11
E.db["unitframe"]["units"]["target"]["raidRoleIcons"]["enable"] = false
E.db["unitframe"]["units"]["target"]["threatStyle"] = "NONE"
E.db["unitframe"]["units"]["target"]["width"] = 101
E.db["unitframe"]["units"]["targettarget"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["targettarget"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["targettarget"]["debuffs"]["enable"] = false
E.db["unitframe"]["units"]["targettarget"]["enable"] = false
E.db["unitframe"]["units"]["targettarget"]["fader"]["enable"] = false
E.db["unitframe"]["units"]["targettarget"]["fader"]["range"] = false
E.db["unitframe"]["units"]["targettarget"]["height"] = 30
E.db["unitframe"]["units"]["targettarget"]["name"]["text_format"] = "[name:veryshort]"
E.db["unitframe"]["units"]["targettarget"]["power"]["enable"] = false
E.db["unitframe"]["units"]["targettarget"]["power"]["height"] = 3
E.db["unitframe"]["units"]["targettarget"]["width"] = 75
E.db["unitframe"]["units"]["targettargettarget"]["buffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["targettargettarget"]["buffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["targettargettarget"]["debuffs"]["countFont"] = "Beep-Black"
E.db["unitframe"]["units"]["targettargettarget"]["debuffs"]["countFontOutline"] = "SHADOWOUTLINE"
E.db["unitframe"]["units"]["targettargettarget"]["power"]["height"] = 3
-- Gloable account settings below
E.global["L1UI"]["scaled"] = true
E.global["datatexts"]["customPanels"]["Info Panel"]["fonts"]["font"] = "Beep-Black"
E.global["datatexts"]["customPanels"]["Info Panel"]["fonts"]["fontOutline"] = "SHADOWOUTLINE"
E.global["datatexts"]["customPanels"]["Info Panel"]["name"] = "Info Panel"
E.global["datatexts"]["settings"]["System"]["ShowOthers"] = false
E.global["datatexts"]["settings"]["System"]["latency"] = "HOME"
-- Private account settings below
E.private["WT"]["tooltips"]["icon"] = false
E.private["WT"]["unitFrames"]["roleIcon"]["enable"] = false
E.private["install_complete"] = 13.7
E.private["skins"]["parchmentRemoverEnable"] = true

		-- If you want to modify the base layout according to
		-- certain conditions then this is how you could do it
		if layout == "tank" then
			-- Make some changes to the layout posted above
		elseif layout == "dps" then
			-- Make some other changes
		elseif layout == "healer" then
			-- Make some different changes
		end

	-- This section at the bottom is just to update ElvUI and display a message

	-- Update ElvUI
	E:StaggeredUpdateAll()

	-- Show message about layout being set
	PluginInstallStepComplete.message = "Layout Set"
	PluginInstallStepComplete:Show()
end

-- This function is executed when you press "Skip Process" or "Finished" in the installer.
local function InstallComplete()
	if GetCVarBool("Sound_EnableMusic") then
		StopMusic()
	end

	-- Set a variable tracking the version of the addon when layout was installed
	E.db[MyPluginName].install_version = Version

	ReloadUI()
end

-- This is the data we pass on to the ElvUI Plugin Installer.
-- The Plugin Installer is reponsible for displaying the install guide for this layout.
local InstallerData = {
	Title = format("|cff4beb2c%s %s|r", "AscendedUI", "Installation"),
	Name = MyPluginName,
	-- Uncomment the line below f you have a logo you want to use, otherwise it uses the one from ElvUI
	tutorialImage = "Interface\\AddOns\\AscendedUI\\logo.png",
    tutorialImageSize = {158, 128},
    tutorialImagePoint = {0, 17},
    Pages = {
		[1] = function()
			PluginInstallFrame.SubTitle:SetFormattedText("Welcome to the installation for %s.", MyPluginName)
			PluginInstallFrame.Desc1:SetText("This installation process will guide you through a few steps and apply settings to your current ElvUI profile. If you want to be able to go back to your original settings then create a new profile before going through this installation process.")
			PluginInstallFrame.Desc2:SetText("Please press the continue button if you wish to go through the installation process, otherwise click the 'Skip Process' button.")
			PluginInstallFrame.Option1:Show()
			PluginInstallFrame.Option1:SetScript("OnClick", InstallComplete)
			PluginInstallFrame.Option1:SetText("Skip Process")
		end,
		[2] = function()
			PluginInstallFrame.SubTitle:SetText("Layouts")
			PluginInstallFrame.Desc1:SetText("These are the layouts that are available. Please click a button below to apply the layout of your choosing.")
			PluginInstallFrame.Desc2:SetText("Importance: |cff07D400High|r")
			PluginInstallFrame.Option1:Show()
			PluginInstallFrame.Option1:SetScript("OnClick", function() SetupLayout("tank") end)
			PluginInstallFrame.Option1:SetText("AscendedUI")
		end,
		[3] = function()
			PluginInstallFrame.SubTitle:SetText(L["Details profile"])
			PluginInstallFrame.Desc1:SetText(L["Please click the button below to apply AscendedUI profile for Details! Damage Meter."])
			PluginInstallFrame.Desc2:SetText(format('|cff4beb2c%s', L["Recommended step. Should not be skipped."]))
			PluginInstallFrame.Option1:Show()
			PluginInstallFrame.Option1:SetScript('OnClick', function() Private:Setup_Details(true) end)
			PluginInstallFrame.Option1:SetText(L["Setup Details"])
		end,
		[4] = function()
			PluginInstallFrame.SubTitle:SetText("Installation Complete")
			PluginInstallFrame.Desc1:SetText("You have completed the installation process.")
			PluginInstallFrame.Desc2:SetText("Please click the button below in order to finalize the process and automatically reload your UI.")
			PluginInstallFrame.Option1:Show()
			PluginInstallFrame.Option1:SetScript("OnClick", InstallComplete)
			PluginInstallFrame.Option1:SetText("Finished")
		end,
	},
	StepTitles = {
		[1] = "Welcome",
		[2] = "Layouts",
		[3] = 'Details',
		[4] = "Installation Complete",
		
	},
	StepTitlesColor = {1, 1, 1},
	StepTitlesColorSelected = {0, 179/255, 1},
	StepTitleWidth = 200,
	StepTitleButtonWidth = 180,
	StepTitleTextJustification = "RIGHT",
}

-- This function holds the options table which will be inserted into the ElvUI config
local function InsertOptions()
	E.Options.args.MyPluginName = {
		order = 100,
		type = "group",
		name = format("|cff4beb2c%s|r", MyPluginName),
		args = {
			header1 = {
				order = 1,
				type = "header",
				name = MyPluginName,
			},
			description1 = {
				order = 2,
				type = "description",
				name = format("%s is a layout for ElvUI.", MyPluginName),
			},
			spacer1 = {
				order = 3,
				type = "description",
				name = "\n\n\n",
			},
			header2 = {
				order = 4,
				type = "header",
				name = "Installation",
			},
			description2 = {
				order = 5,
				type = "description",
				name = "The installation guide should pop up automatically after you have completed the ElvUI installation. If you wish to re-run the installation process for this layout then please click the button below.",
			},
			spacer2 = {
				order = 6,
				type = "description",
				name = "",
			},
			install = {
				order = 7,
				type = "execute",
				name = "Install",
				desc = "Run the installation process.",
				func = function() E:GetModule("PluginInstaller"):Queue(InstallerData); E:ToggleOptions(); end,
			},
		},
	}
end

-- Create a unique table for our plugin
P[MyPluginName] = {}

-- This function will handle initialization of the addon
function mod:Initialize()
	-- Initiate installation process if ElvUI install is complete and our plugin install has not yet been run
	if E.private.install_complete and E.db[MyPluginName].install_version == nil then
		E:GetModule("PluginInstaller"):Queue(InstallerData)
	end

	-- Insert our options table when ElvUI config is loaded
	EP:RegisterPlugin(addon, InsertOptions)
end

-- Register module with callback so it gets initialized when ready
E:RegisterModule(mod:GetName())